### ISSUE TITLE
Couldn't control thickness.

### ISSUE THREAD

**Issue by veeru412** [Dread5/Outline-Shader-URP-#1]
I have a requirement that whenever an object is clicked i need to enable out line only for that object. if it is deselected out line has to be turn off. How can i do that?

**Comment by jpgtzg** [comment]
You can easily do this by sending a raycast from the mousePosition (or camera position) to the world. When the ray hits an object with appropiate name (or tag) and the mouse is clicked, you save this gameobject into a variable called currentSelection and then you change the current shader. Once you stop clicking, you simply revert back to the old shader. Here is a code I made for a selection system similar to what you are looking for. It works by changing the material, but you could easily change it to change the shader. 

 
        var ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        if(currentSelection != null)
        {
            currentSelection = null;
            var selectionRenderer = currentSelection.GetComponent<Renderer>();
            handImage.SetActive(false);
            selectionRenderer.material = defaultMaterial;
        }
        RaycastHit hit;
        if(Physics.Raycast(ray, out hit, range))
        {
            var selection = hit.transform;
            if(selection.CompareTag(pickableTag))
            {
                var selectionRenderer = selection.GetComponent<Renderer>();
                defaultMaterial = selectionRenderer.material;
                if (selectionRenderer != null)
                {
                    selectionRenderer.material = highlightMaterial;
                    handImage.SetActive(true);
                    if (getMouseButtonDown())
                    {
                        inventory.pick(selection);
                    }
                }
                currentSelection = selection;
            }         
        }
